### ISSUE TITLE
Version 1.0.4 MoonPhaseMapper only returns some of the phases

### ISSUE THREAD

**Issue by ggocek** [webbwebbwebb/suncalcsharp#1]
It seems like MoonPhaseMapper in version 1.0.4 (latest available) only returns some of the phases. For example, it never returns FirstQuarter. Am I missing something?

It would also be nice if this package could have small images for each phase, and a language mapper, along with the enum name. So, FirstQuarter would have the enum name, and "First Quarter" for English, and a JPG file for a first quarter moon phase. Or maybe a spot where the client application can set an image URL for each phase.

I will probably just grab the source and fix it for myself, which is unfortunate for an otherwise usable package.

**Comment by webbwebbwebb** [comment]
You're right, the mapper is missing two of the phases.  I've fixed the mapper and created a new version (1.05) of the nuget package.

I won't be adding any images or language mapping - everyone will have a different use case, and it's beyond the scope of this library.

**Comment by ggocek** [comment]
Thanks!
